### ISSUE TITLE
Crash on config check

### ISSUE THREAD

**Issue by Alex-the-666** [FossilsArcheologyRevival/FossilsArcheology1.7#407]
I was looking at the config options and clicked the tab generation. I assume this crash is because the code doesnt know how to handle the array of numbers for oreGenerationDimensions.

"Connected to the target VM, address: '127.0.0.1:59624', transport: 'socket'
[17:46:10] [main/INFO] [GradleStart]: Extra: []
[17:46:10] [main/INFO] [GradleStart]: Found and added coremod: net.ilexiconn.llibrary.server.asm.LLibraryPlugin
[17:46:10] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/alexr_000/.gradle/caches/minecraft/assets, --assetIndex, 1.7.10, --accessToken, {REDACTED}, --version, 1.7.10, --tweakClass, cpw.mods.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[17:46:10] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[17:46:11] [main/INFO] [FML]: Forge Mod Loader version 7.99.36.1558 for Minecraft 1.7.10 loading
[17:46:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_05, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jdk1.8.0_05\jre
[17:46:11] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[17:46:11] [main/INFO] [FML]: Found a command line coremod : net.ilexiconn.llibrary.server.asm.LLibraryPlugin
[17:46:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[17:46:11] [main/INFO] [GradleStart]: Injecting location in coremod cpw.mods.fml.relauncher.FMLCorePlugin
[17:46:11] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[17:46:11] [main/INFO] [GradleStart]: Injecting location in coremod net.ilexiconn.llibrary.server.asm.LLibraryPlugin
[17:46:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:46:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:11] [main/ERROR] [FML]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[17:46:16] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[17:46:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:16] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:46:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:46:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[17:46:18] [main/INFO] [GradleStart]: Remapping AccessTransformer rules...
[17:46:18] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[17:46:18] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[17:46:18] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:46:20] [main/INFO]: Setting user: Player890
[17:46:23] [Client thread/INFO]: LWJGL Version: 2.9.1
[17:46:25] [Client thread/INFO] [STDOUT]: [cpw.mods.fml.client.SplashProgress:start:188]: ---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 7/15/16 5:46 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 750144608 bytes (715 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3316' Renderer: 'Intel(R) HD Graphics 4400'
[17:46:25] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[17:46:25] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1558 Initialized
[17:46:25] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[17:46:25] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[17:46:26] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[17:46:26] [Client thread/INFO] [FML]: Searching C:\Users\alexr_000\Desktop\Mods_New\FossilsArcheology1.7\minecraft\mods for mods
[17:47:05] [Client thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[17:47:08] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, fossil, llibrary] at CLIENT
[17:47:08] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, fossil, llibrary] at SERVER
[17:47:10] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Fossils and Archeology Revival, FMLFileResourcePack:LLibrary
[17:47:11] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[17:47:11] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[17:47:11] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[17:47:11] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:47:11] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:47:17] [Client thread/INFO] [FML]: Applying holder lookups
[17:47:17] [Client thread/INFO] [FML]: Holder lookups applied
[17:47:17] [Client thread/INFO] [FML]: Injecting itemstacks
[17:47:17] [Client thread/INFO] [FML]: Itemstack injection complete
[17:47:17] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:47:17] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[17:47:17] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[17:47:17] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:47:17] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[17:47:18] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:47:18] [Sound Library Loader/INFO]: Sound engine started
[17:47:20] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[17:47:20] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[17:47:21] [Client thread/INFO] [FML]: Injecting itemstacks
[17:47:21] [Client thread/INFO] [FML]: Itemstack injection complete
[17:47:21] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[17:47:21] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Fossils and Archeology Revival, FMLFileResourcePack:LLibrary
[17:47:23] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[17:47:28] [Client thread/INFO]: Created: 512x512 textures/items-atlas
[17:47:28] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:47:28] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[17:47:28] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[17:47:28] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:47:28] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:47:28] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[17:47:28] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[17:47:28] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:47:28] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[17:47:28] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[17:47:28] [Sound Library Loader/INFO]: Sound engine started
[17:48:42] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1168) ~[EntityRenderer.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1067) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:962) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source) [start/:?]
	at GradleStart.main(Unknown Source) [start/:?]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_05]
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_05]
	at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_05]
	at net.ilexiconn.llibrary.client.gui.config.ConfigGUI.createPropertyElement(ConfigGUI.java:150) ~[ConfigGUI.class:?]
	at net.ilexiconn.llibrary.client.gui.config.ConfigGUI.drawScreen(ConfigGUI.java:112) ~[ConfigGUI.class:?]
	at net.ilexiconn.llibrary.client.gui.ElementGUI.drawScreen(ElementGUI.java:48) ~[ElementGUI.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137) ~[EntityRenderer.class:?]
	... 11 more
[17:48:42] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:388]: ---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 7/15/16 5:48 PM
Description: Rendering screen

java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at net.ilexiconn.llibrary.client.gui.config.ConfigGUI.createPropertyElement(ConfigGUI.java:150)
	at net.ilexiconn.llibrary.client.gui.config.ConfigGUI.drawScreen(ConfigGUI.java:112)
	at net.ilexiconn.llibrary.client.gui.ElementGUI.drawScreen(ElementGUI.java:48)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1067)
	at net.minecraft.client.Minecraft.run(Minecraft.java:962)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.valueOf(Integer.java:766)
	at net.ilexiconn.llibrary.client.gui.config.ConfigGUI.createPropertyElement(ConfigGUI.java:150)
	at net.ilexiconn.llibrary.client.gui.config.ConfigGUI.drawScreen(ConfigGUI.java:112)
	at net.ilexiconn.llibrary.client.gui.ElementGUI.drawScreen(ElementGUI.java:48)

-- Screen render details --
Details:
	Screen name: fossilsarcheology.client.gui.RevivalConfigGUI
	Mouse location: Scaled: (64, 125). Absolute: (193, 626)
	Screen size: Scaled: (640, 335). Absolute: (1920, 1003). Scale factor of 3
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1067)
	at net.minecraft.client.Minecraft.run(Minecraft.java:962)
	at net.minecraft.client.main.Main.main(Main.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 922049880 bytes (879 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJA	llibrary{1.4.0} [LLibrary] (llibrary-1.4.0-1.7.10-dev.jar) 
	UCHIJA	fossil{7.3.1-develop} [Fossils and Archeology Revival] (FossilsArcheology1.7) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3316' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3316, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[17:48:42] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:displayCrashReport:398]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\alexr_000\Desktop\Mods_New\FossilsArcheology1.7\minecraft\.\crash-reports\crash-2016-07-15_17.48.42-client.txt
Disconnected from the target VM, address: '127.0.0.1:59624', transport: 'socket'
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

Process finished with exit code -1

**Comment by iLexiconn** [comment]
Create this issue on the llibrary repo, not here
